import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Label } from "./ui/label";
import { Switch } from "./ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Slider } from "./ui/slider";
import { Badge } from "./ui/badge";
import { Info } from "lucide-react";
import type { MergeStrategy } from "../lib/hybrid-ensemble";

interface HybridModeConfig {
  enabled: boolean;
  strategy: MergeStrategy;
  maxModels: number;
}

interface HybridModeSettingsProps {
  config: HybridModeConfig;
  onChange: (config: HybridModeConfig) => void;
}

const STRATEGY_INFO: Record<MergeStrategy, { name: string; description: string; speed: string; quality: string }> = {
  "streaming-race": {
    name: "Streaming Race",
    description: "First model to respond wins - fastest response time",
    speed: "⚡ Fastest",
    quality: "⭐⭐⭐ Good"
  },
  "parallel-merge": {
    name: "Parallel Merge",
    description: "Query all models simultaneously and merge best responses",
    speed: "⚡⚡ Fast",
    quality: "⭐⭐⭐⭐ Great"
  },
  "best-of-n": {
    name: "Best of N",
    description: "Pick the single highest quality response from all models",
    speed: "⚡⚡ Fast",
    quality: "⭐⭐⭐⭐ Great"
  },
  "consensus": {
    name: "Consensus",
    description: "Find agreement and common elements across all responses",
    speed: "⚡⚡⚡ Medium",
    quality: "⭐⭐⭐⭐⭐ Excellent"
  },
  "weighted": {
    name: "Weighted Merge",
    description: "Combine responses with quality-based weights",
    speed: "⚡⚡⚡ Medium",
    quality: "⭐⭐⭐⭐ Great"
  },
  "synthesis": {
    name: "Synthesis",
    description: "Synthesize all responses into comprehensive answer",
    speed: "⚡⚡⚡ Medium",
    quality: "⭐⭐⭐⭐⭐ Excellent"
  },
  "chain-of-thought": {
    name: "Chain of Thought",
    description: "Sequential refinement through multiple models",
    speed: "⚡⚡⚡⚡ Slow",
    quality: "⭐⭐⭐⭐⭐ Best"
  },
  "voting": {
    name: "Voting",
    description: "Majority consensus across model responses",
    speed: "⚡⚡⚡ Medium",
    quality: "⭐⭐⭐⭐ Great"
  }
};

export function HybridModeSettings({ config, onChange }: HybridModeSettingsProps) {
  const [localConfig, setLocalConfig] = useState<HybridModeConfig>(config);

  const handleToggle = (enabled: boolean) => {
    const newConfig = { ...localConfig, enabled };
    setLocalConfig(newConfig);
    onChange(newConfig);
  };

  const handleStrategyChange = (strategy: MergeStrategy) => {
    const newConfig = { ...localConfig, strategy };
    setLocalConfig(newConfig);
    onChange(newConfig);
  };

  const handleMaxModelsChange = (value: number[]) => {
    const newConfig = { ...localConfig, maxModels: value[0] };
    setLocalConfig(newConfig);
    onChange(newConfig);
  };

  const selectedStrategyInfo = STRATEGY_INFO[localConfig.strategy];

  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>🚀 Hybrid Ensemble Mode</CardTitle>
            <CardDescription>
              Combine multiple AI models for superior responses
            </CardDescription>
          </div>
          <Switch
            checked={localConfig.enabled}
            onCheckedChange={handleToggle}
          />
        </div>
      </CardHeader>

      {localConfig.enabled && (
        <CardContent className="space-y-6">
          {/* Info Banner */}
          <div className="flex items-start gap-3 rounded-lg bg-blue-50 dark:bg-blue-950 p-4 text-sm">
            <Info className="h-5 w-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
            <div className="space-y-1">
              <p className="font-medium text-blue-900 dark:text-blue-100">
                Hybrid Mode combines all free OpenRouter models
              </p>
              <p className="text-blue-700 dark:text-blue-300">
                Your response will be generated by merging outputs from up to {localConfig.maxModels} AI models,
                providing superior quality similar to Claude and ChatGPT.
              </p>
            </div>
          </div>

          {/* Merge Strategy */}
          <div className="space-y-2">
            <Label htmlFor="strategy-select">Merge Strategy</Label>
            <Select value={localConfig.strategy} onValueChange={handleStrategyChange}>
              <SelectTrigger id="strategy-select">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {(Object.entries(STRATEGY_INFO) as [MergeStrategy, typeof STRATEGY_INFO[MergeStrategy]][]).map(([key, info]) => (
                  <SelectItem key={key} value={key}>
                    <div className="flex flex-col items-start py-1">
                      <span className="font-medium">{info.name}</span>
                      <span className="text-xs text-muted-foreground">{info.description}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            {/* Strategy Info */}
            <div className="rounded-md bg-muted p-3 space-y-2">
              <div className="flex items-center gap-2">
                <Badge variant="secondary">{selectedStrategyInfo.speed}</Badge>
                <Badge variant="secondary">{selectedStrategyInfo.quality}</Badge>
              </div>
              <p className="text-sm text-muted-foreground">
                {selectedStrategyInfo.description}
              </p>
            </div>
          </div>

          {/* Max Models Slider */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="max-models-slider">Maximum Models</Label>
              <span className="text-sm font-medium">{localConfig.maxModels}</span>
            </div>
            <Slider
              id="max-models-slider"
              min={3}
              max={20}
              step={1}
              value={[localConfig.maxModels]}
              onValueChange={handleMaxModelsChange}
              className="w-full"
            />
            <p className="text-xs text-muted-foreground">
              More models = higher quality but slower response time
            </p>
          </div>

          {/* Performance Estimate */}
          <div className="rounded-lg border p-4 space-y-2">
            <h4 className="text-sm font-medium">Expected Performance</h4>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-muted-foreground">Response Time</p>
                <p className="font-medium">
                  {localConfig.strategy === "streaming-race" ? "1-3 sec" :
                   localConfig.strategy === "chain-of-thought" ? "10-30 sec" :
                   "3-10 sec"}
                </p>
              </div>
              <div>
                <p className="text-muted-foreground">Quality Level</p>
                <p className="font-medium">
                  {localConfig.strategy === "chain-of-thought" || localConfig.strategy === "consensus" || localConfig.strategy === "synthesis"
                    ? "Claude/GPT-4 Level"
                    : "GPT-3.5/Claude Instant Level"}
                </p>
              </div>
            </div>
          </div>

          {/* Cost Info */}
          <div className="text-center p-3 rounded-lg bg-green-50 dark:bg-green-950">
            <p className="text-sm font-medium text-green-900 dark:text-green-100">
              💰 100% Free - All models are free tier
            </p>
          </div>
        </CardContent>
      )}
    </Card>
  );
}
